### ISSUE TITLE
just wanted to say thanks

### ISSUE THREAD

**Issue by ghvader** [tusc/ntopng-udm#10]
@tusc I wanted to say thanks for the NTP docker build you did, but i think they locked that thread over at the unifi site.
couldn't figure out a way to msg you there. so just wanted to drop a note to say thanks for that, it was exactly what i was looking for!

**Comment by tusc** [comment]
Glad I could help! You can search for my profile at the unifi site and select "MESSAGE" from the top right of the profile screen. I'm tusc69 on that forum.
