### ISSUE TITLE
use /mnt/data_ext for more disk space when using a hard drive installed in UDM Pro

### ISSUE THREAD

**Issue by jgarland79** [tusc/ntopng-udm#12]
I've installed a 256G SSD in my UDM Pro and I've deployed this project on that drive.

Here's the command I use to start the container:

<pre>
podman run -d --net=host --restart always \
   --name ntopng \
   -v /mnt/data_ext/ntopng/GeoIP.conf:/etc/GeoIP.conf \
   -v /mnt/data_ext/ntopng/ntopng.conf:/etc/ntopng/ntopng.conf \
   -v /mnt/data_ext/ntopng/redis.conf:/etc/redis/redis.conf \
   -v /mnt/data_ext/ntopng/lib:/var/lib/ntopng \
   docker.io/tusc/ntopng-udm:latest

**Comment by tusc** [comment]
Thanks, yes you can use the path to the external drive as the location for the ntopng config/database files. I will update the readme to include this.

**Comment by tomwardrop** [comment]
That's really useful thanks! - Any updates to 4.2.0 coming up?

**Comment by tusc** [comment]
4.2 was just pushed out yesterday.
