### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by net47** [tusc/ntopng-udm#14]
Hi,

first of all, many thanks for your work, ntopng works like a charm on UDM pro!

How is it possible to update ntopng to a new version? I see in the Dockerfile you just copy the "200711" packages to /tmp and install them. Is it possible to simply replace the current "ntopng_4.1.200711-10754_arm64.deb" with a current one, e.g. "ntopng_4.2.201120-12281_amd64.deb" (from https://packages.ntop.org/apt-stable/buster/x64/) ?

Additionally: what's the "ntopng-data_4.1.200711_all.deb" package? Is this mandatory?

best
Daniel

**Comment by tomwardrop** [comment]
+1

**Comment by buzzke** [comment]
+1

**Comment by Mahdi-GoVanguard** [comment]
+1

**Comment by Mahdi-GoVanguard** [comment]
@net47 just noting that you referenced an ARM deb and suggested trying to use an x86 deb. In it's place... must be ARM.

> Hi,
> 
> first of all, many thanks for your work, ntopng works like a charm on UDM pro!
> 
> How is it possible to update ntopng to a new version? I see in the Dockerfile you just copy the "200711" packages to /tmp and install them. Is it possible to simply replace the current "ntopng_4.1.200711-10754_arm64.deb" with a current one, e.g. "ntopng_4.2.201120-12281_amd64.deb" (from https://packages.ntop.org/apt-stable/buster/x64/) ?
> 
> Additionally: what's the "ntopng-data_4.1.200711_all.deb" package? Is this mandatory?
> 
> best
> Daniel

**Comment by tusc** [comment]
I've just updated ntopng to the 4.2 release. You should be able to pull the new image down from docker hub and start the new instance.

**Comment by tusc** [comment]
> Hi,
> 
> first of all, many thanks for your work, ntopng works like a charm on UDM pro!
> 
> How is it possible to update ntopng to a new version? I see in the Dockerfile you just copy the "200711" packages to /tmp and install them. Is it possible to simply replace the current "ntopng_4.1.200711-10754_arm64.deb" with a current one, e.g. "ntopng_4.2.201120-12281_amd64.deb" (from https://packages.ntop.org/apt-stable/buster/x64/) ?
> 
> Additionally: what's the "ntopng-data_4.1.200711_all.deb" package? Is this mandatory?
> 
> best
> Daniel

Daniel,

the referenced deb files I use in the Dockerfile are ARM64 versions which I build. They are not provided by the ntopng team. I'm in talks with them on incorporating the ARM64 builds so they will eventually offer an official build and optionally the enterprise/pro license will be available.

**Comment by buzzke** [comment]
Thanx for the update!

**Comment by net47** [comment]
> > Hi,
> > first of all, many thanks for your work, ntopng works like a charm on UDM pro!
> > How is it possible to update ntopng to a new version? I see in the Dockerfile you just copy the "200711" packages to /tmp and install them. Is it possible to simply replace the current "ntopng_4.1.200711-10754_arm64.deb" with a current one, e.g. "ntopng_4.2.201120-12281_amd64.deb" (from https://packages.ntop.org/apt-stable/buster/x64/) ?
> > Additionally: what's the "ntopng-data_4.1.200711_all.deb" package? Is this mandatory?
> > best
> > Daniel
> 
> Daniel,
> 
> the referenced deb files I use in the Dockerfile are ARM64 versions which I build. They are not provided by the ntopng team. I'm in talks with them on incorporating the ARM64 builds so they will eventually offer an official build and optionally the enterprise/pro license will be available.

Thanks a lot!
