### ISSUE TITLE
Externalize ntopng configs using docker volume mounts

### ISSUE THREAD

**Issue by boostchicken** [tusc/ntopng-udm#2]
This is a best practice and should ensure any data is not lost during firmware updates.

**Comment by tusc** [comment]
Good point boostchicken. I think the ntopng.conf file would be suited for this. I should probably create a directory under /mnt/data to store, no?

**Comment by rodalpho** [comment]
That would be perfect, that's where I store my Adguard Home container info.

**Comment by tusc** [comment]
Just updated the code for these changes. Let me know if it works out.

**Comment by boostchicken** [comment]
@tusc looks good to me installing now.
