### ISSUE TITLE
Can you add steps for Geolocation support in this UDMP docker?

### ISSUE THREAD

**Issue by rcmpayne** [tusc/ntopng-udm#3]
Geolocation support is not enabled, please follow the instructions in the documentation  to enable it.
      https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md

Not sure how much changes with the above steps.

**Comment by tusc** [comment]
@rcmpayne this was added yesterday.  https://github.com/tusc/ntopng-udm#geoip-integration

Can you see if it meets your requirements?

**Comment by tusc** [comment]
feature has been implemented.
