### ISSUE TITLE
Enhancement: External Redis Server

### ISSUE THREAD

**Issue by boostchicken** [tusc/ntopng-udm#4]
Some people might already be running Redis, it would be great to be able to utilize existing Redis clusters.

**Comment by tusc** [comment]
This can be done from the ntopng.conf file. Just add this parameter:

[--redis|-r] <fmt>        | Redis connection. <fmt> is specified as
                                    | [h[:port[:pwd]]][@db-id] where db-id
                                    | identifies the database Id (default 0).
                                    | h is the host running Redis (default
                                    | localhost), optionally followed by a
                                    |  ':'-separated port (default 6379).
                                    | A password can be specified after
                                    | the port when Redis auth is required.
                                    | By default password auth is disabled.
                                    | On unix <fmt> can also be the redis socket file path.
                                    | Port is ignored for socket-based connections.
                                    | Examples:
                                    | -r @2
                                    | -r 129.168.1.3
                                    | -r 129.168.1.3:6379@3
                                    | -r 129.168.1.3:6379:nt0pngPwD@0
                                    | -r /var/run/redis/redis.sock
                                    | -r /var/run/redis/redis.sock@2

**Comment by boostchicken** [comment]
Yes, but your redis server always starts in the image though?
